"""Committed default CATv1 experiment per ``(assay, biosample)`` pair.

GENERATED FILE -- do not edit by hand.  Regenerate with:

    python scripts/generate_catv1_defaults.py

Maps a ``(assay, biosample)`` pair to the single CATv1 experiment that
``load_pretrained_model(assay=..., cell_type=...)`` resolves to.  See the
generator's module docstring for why this is committed rather than
computed at runtime, and for the selection rules.

492 pairs, of which 162 hold more than one experiment.
9 are pinned to ChromBPNet's experiment for cross-oracle parity.
"""

# (assay, biosample) -> (experiment_accession, n_candidates, reason)
CATV1_DEFAULT_EXPERIMENT: dict[tuple[str, str], tuple[str, int, str]] = {
    ('ATAC', 'A549'): ('ENCSR220ASC', 2, 'best-count-pearson'),
    ('ATAC', 'B cell'): ('ENCSR603LVR', 1, 'only-candidate'),
    ('ATAC', 'CD4-positive, CD25-positive, alpha-beta regulatory T cell'): ('ENCSR504OUW', 2, 'best-count-pearson'),
    ('ATAC', 'CD4-positive, alpha-beta T cell'): ('ENCSR841LHT', 1, 'only-candidate'),
    ('ATAC', 'CD8-positive, alpha-beta T cell'): ('ENCSR476VJY', 1, 'only-candidate'),
    ('ATAC', 'DND-41'): ('ENCSR660WSB', 1, 'only-candidate'),
    ('ATAC', 'GM12878'): ('ENCSR637XSC', 2, 'chrombpnet-parity'),
    ('ATAC', 'GM18498'): ('ENCSR924SDV', 1, 'only-candidate'),
    ('ATAC', 'GM18499'): ('ENCSR700HPA', 1, 'only-candidate'),
    ('ATAC', 'GM18502'): ('ENCSR241VGH', 1, 'only-candidate'),
    ('ATAC', 'GM18505'): ('ENCSR084FHK', 1, 'only-candidate'),
    ('ATAC', 'GM18508'): ('ENCSR357WQH', 1, 'only-candidate'),
    ('ATAC', 'GM18511'): ('ENCSR253QLW', 1, 'only-candidate'),
    ('ATAC', 'GM18517'): ('ENCSR442OAV', 1, 'only-candidate'),
    ('ATAC', 'GM18519'): ('ENCSR312UCH', 1, 'only-candidate'),
    ('ATAC', 'GM18520'): ('ENCSR762YFD', 1, 'only-candidate'),
    ('ATAC', 'GM18858'): ('ENCSR011NJP', 1, 'only-candidate'),
    ('ATAC', 'GM18861'): ('ENCSR628PLS', 1, 'only-candidate'),
    ('ATAC', 'GM18867'): ('ENCSR492FJO', 1, 'only-candidate'),
    ('ATAC', 'GM18868'): ('ENCSR580JBA', 1, 'only-candidate'),
    ('ATAC', 'GM18870'): ('ENCSR684KUG', 1, 'only-candidate'),
    ('ATAC', 'GM18873'): ('ENCSR304ZDQ', 1, 'only-candidate'),
    ('ATAC', 'GM18907'): ('ENCSR487QSB', 1, 'only-candidate'),
    ('ATAC', 'GM18909'): ('ENCSR917WJS', 1, 'only-candidate'),
    ('ATAC', 'GM19023'): ('ENCSR512FHU', 1, 'only-candidate'),
    ('ATAC', 'GM19025'): ('ENCSR419UYY', 1, 'only-candidate'),
    ('ATAC', 'GM19035'): ('ENCSR637MUF', 1, 'only-candidate'),
    ('ATAC', 'GM19043'): ('ENCSR409YCK', 1, 'only-candidate'),
    ('ATAC', 'GM19324'): ('ENCSR425WQW', 1, 'only-candidate'),
    ('ATAC', 'GM19328'): ('ENCSR383RDZ', 1, 'only-candidate'),
    ('ATAC', 'GM19351'): ('ENCSR231BZU', 1, 'only-candidate'),
    ('ATAC', 'GM19372'): ('ENCSR335JVB', 1, 'only-candidate'),
    ('ATAC', 'GM19395'): ('ENCSR372IGW', 1, 'only-candidate'),
    ('ATAC', 'GM19397'): ('ENCSR839IAD', 1, 'only-candidate'),
    ('ATAC', 'GM19438'): ('ENCSR134OSR', 1, 'only-candidate'),
    ('ATAC', 'GM19452'): ('ENCSR454UTH', 1, 'only-candidate'),
    ('ATAC', 'GM19455'): ('ENCSR706GDQ', 1, 'only-candidate'),
    ('ATAC', 'GM19463'): ('ENCSR712ZRY', 1, 'only-candidate'),
    ('ATAC', 'GM19467'): ('ENCSR635CAC', 1, 'only-candidate'),
    ('ATAC', 'GM19468'): ('ENCSR635AIF', 1, 'only-candidate'),
    ('ATAC', 'GM21360'): ('ENCSR105SCQ', 1, 'only-candidate'),
    ('ATAC', 'GM21367'): ('ENCSR509JPT', 1, 'only-candidate'),
    ('ATAC', 'GM21381'): ('ENCSR512YXO', 1, 'only-candidate'),
    ('ATAC', 'GM21390'): ('ENCSR024WOD', 1, 'only-candidate'),
    ('ATAC', 'GM21423'): ('ENCSR902CFR', 1, 'only-candidate'),
    ('ATAC', 'GM21447'): ('ENCSR424KQH', 1, 'only-candidate'),
    ('ATAC', 'GM21515'): ('ENCSR960KGO', 1, 'only-candidate'),
    ('ATAC', 'GM21526'): ('ENCSR408IVU', 1, 'only-candidate'),
    ('ATAC', 'GM21528'): ('ENCSR939EVW', 1, 'only-candidate'),
    ('ATAC', 'GM21529'): ('ENCSR954BDA', 1, 'only-candidate'),
    ('ATAC', 'GM21576'): ('ENCSR122NDR', 1, 'only-candidate'),
    ('ATAC', 'GM21619'): ('ENCSR214EIV', 1, 'only-candidate'),
    ('ATAC', 'GM21717'): ('ENCSR422RPD', 1, 'only-candidate'),
    ('ATAC', 'GM21723'): ('ENCSR233HSC', 1, 'only-candidate'),
    ('ATAC', 'GM21737'): ('ENCSR315QWI', 1, 'only-candidate'),
    ('ATAC', 'GM21786'): ('ENCSR275LCF', 1, 'only-candidate'),
    ('ATAC', 'GM21825'): ('ENCSR641KNU', 1, 'only-candidate'),
    ('ATAC', 'GM23338'): ('ENCSR485TLP', 1, 'only-candidate'),
    ('ATAC', 'HCT116'): ('ENCSR872WGW', 1, 'only-candidate'),
    ('ATAC', 'HG02571'): ('ENCSR400ISH', 1, 'only-candidate'),
    ('ATAC', 'HG02588'): ('ENCSR189VFC', 1, 'only-candidate'),
    ('ATAC', 'HG02610'): ('ENCSR905PWV', 1, 'only-candidate'),
    ('ATAC', 'HG02623'): ('ENCSR821JHD', 1, 'only-candidate'),
    ('ATAC', 'HG02642'): ('ENCSR821QHC', 1, 'only-candidate'),
    ('ATAC', 'HG02678'): ('ENCSR180HEL', 1, 'only-candidate'),
    ('ATAC', 'HG02759'): ('ENCSR144ZXR', 1, 'only-candidate'),
    ('ATAC', 'HG02763'): ('ENCSR404OEO', 1, 'only-candidate'),
    ('ATAC', 'HG02798'): ('ENCSR524CPZ', 1, 'only-candidate'),
    ('ATAC', 'HG02840'): ('ENCSR854ZBA', 1, 'only-candidate'),
    ('ATAC', 'HG02852'): ('ENCSR368FYV', 1, 'only-candidate'),
    ('ATAC', 'HG02870'): ('ENCSR420RVW', 1, 'only-candidate'),
    ('ATAC', 'HG02884'): ('ENCSR604YEQ', 1, 'only-candidate'),
    ('ATAC', 'HG02885'): ('ENCSR621JYI', 1, 'only-candidate'),
    ('ATAC', 'HG02938'): ('ENCSR920FQJ', 1, 'only-candidate'),
    ('ATAC', 'HG02943'): ('ENCSR123WME', 1, 'only-candidate'),
    ('ATAC', 'HG02970'): ('ENCSR857MCZ', 1, 'only-candidate'),
    ('ATAC', 'HG02973'): ('ENCSR038WVV', 1, 'only-candidate'),
    ('ATAC', 'HG02981'): ('ENCSR208HAP', 1, 'only-candidate'),
    ('ATAC', 'HG03025'): ('ENCSR673ZMQ', 1, 'only-candidate'),
    ('ATAC', 'HG03039'): ('ENCSR381LJX', 1, 'only-candidate'),
    ('ATAC', 'HG03045'): ('ENCSR249FXU', 1, 'only-candidate'),
    ('ATAC', 'HG03060'): ('ENCSR470ZNM', 1, 'only-candidate'),
    ('ATAC', 'HG03064'): ('ENCSR487SOP', 1, 'only-candidate'),
    ('ATAC', 'HG03066'): ('ENCSR040PBN', 1, 'only-candidate'),
    ('ATAC', 'HG03095'): ('ENCSR359HFH', 1, 'only-candidate'),
    ('ATAC', 'HG03097'): ('ENCSR608KJD', 1, 'only-candidate'),
    ('ATAC', 'HG03103'): ('ENCSR833ACP', 1, 'only-candidate'),
    ('ATAC', 'HG03108'): ('ENCSR962ITF', 1, 'only-candidate'),
    ('ATAC', 'HG03135'): ('ENCSR096VEO', 1, 'only-candidate'),
    ('ATAC', 'HG03139'): ('ENCSR615YIL', 1, 'only-candidate'),
    ('ATAC', 'HG03159'): ('ENCSR940YDN', 1, 'only-candidate'),
    ('ATAC', 'HG03175'): ('ENCSR305XRF', 1, 'only-candidate'),
    ('ATAC', 'HG03196'): ('ENCSR063UNG', 1, 'only-candidate'),
    ('ATAC', 'HG03280'): ('ENCSR554WGQ', 1, 'only-candidate'),
    ('ATAC', 'HG03342'): ('ENCSR528YDD', 1, 'only-candidate'),
    ('ATAC', 'HG03354'): ('ENCSR025MEO', 1, 'only-candidate'),
    ('ATAC', 'HG03378'): ('ENCSR824DUE', 1, 'only-candidate'),
    ('ATAC', 'HG03432'): ('ENCSR839UOB', 1, 'only-candidate'),
    ('ATAC', 'HG03439'): ('ENCSR376YMU', 1, 'only-candidate'),
    ('ATAC', 'HG03442'): ('ENCSR858GTE', 1, 'only-candidate'),
    ('ATAC', 'HG03457'): ('ENCSR322SBN', 1, 'only-candidate'),
    ('ATAC', 'HG03460'): ('ENCSR345NVR', 1, 'only-candidate'),
    ('ATAC', 'HG03469'): ('ENCSR163KRG', 1, 'only-candidate'),
    ('ATAC', 'HG03520'): ('ENCSR624CTU', 1, 'only-candidate'),
    ('ATAC', 'HG03521'): ('ENCSR594TMY', 1, 'only-candidate'),
    ('ATAC', 'HG03558'): ('ENCSR278JWM', 1, 'only-candidate'),
    ('ATAC', 'HG03565'): ('ENCSR835WBW', 1, 'only-candidate'),
    ('ATAC', 'HG03571'): ('ENCSR000RBT', 1, 'only-candidate'),
    ('ATAC', 'HG03575'): ('ENCSR331JFZ', 1, 'only-candidate'),
    ('ATAC', 'HepG2'): ('ENCSR291GJU', 2, 'chrombpnet-parity'),
    ('ATAC', 'IMR-90'): ('ENCSR200OML', 1, 'chrombpnet-parity'),
    ('ATAC', 'K562'): ('ENCSR868FGK', 4, 'chrombpnet-parity'),
    ('ATAC', 'MCF-7'): ('ENCSR422SUG', 1, 'only-candidate'),
    ('ATAC', 'NCI-H929'): ('ENCSR382LBS', 1, 'only-candidate'),
    ('ATAC', 'PC-3'): ('ENCSR499ASS', 1, 'only-candidate'),
    ('ATAC', 'Panc1'): ('ENCSR591PIX', 1, 'only-candidate'),
    ('ATAC', "Peyer's patch"): ('ENCSR017RQC', 1, 'only-candidate'),
    ('ATAC', 'RWPE2'): ('ENCSR080SNF', 1, 'only-candidate'),
    ('ATAC', 'Right ventricle myocardium inferior'): ('ENCSR855BMI', 1, 'only-candidate'),
    ('ATAC', 'Right ventricle myocardium superior'): ('ENCSR074WMH', 1, 'only-candidate'),
    ('ATAC', 'SK-N-SH'): ('ENCSR587TRP', 1, 'only-candidate'),
    ('ATAC', 'T-cell'): ('ENCSR032MEH', 6, 'best-count-pearson'),
    ('ATAC', 'T-helper 17 cell'): ('ENCSR803FKU', 3, 'best-count-pearson'),
    ('ATAC', 'WTC11'): ('ENCSR541KFY', 1, 'only-candidate'),
    ('ATAC', 'activated B cell'): ('ENCSR659SFK', 1, 'only-candidate'),
    ('ATAC', 'activated CD4-positive, CD25-positive, alpha-beta regulatory T cell'): ('ENCSR094QFZ', 2, 'best-count-pearson'),
    ('ATAC', 'activated CD4-positive, alpha-beta T cell'): ('ENCSR991PBP', 1, 'only-candidate'),
    ('ATAC', 'activated CD8-positive, alpha-beta T cell'): ('ENCSR545UJP', 2, 'best-count-pearson'),
    ('ATAC', 'activated CD8-positive, alpha-beta memory T cell'): ('ENCSR915MTG', 1, 'only-candidate'),
    ('ATAC', 'activated T-cell'): ('ENCSR775KMA', 6, 'best-count-pearson'),
    ('ATAC', 'activated T-helper 17 cell'): ('ENCSR115OIV', 1, 'only-candidate'),
    ('ATAC', 'activated naive CD4-positive, alpha-beta T cell'): ('ENCSR373NFA', 2, 'best-count-pearson'),
    ('ATAC', 'activated naive CD8-positive, alpha-beta T cell'): ('ENCSR983HXF', 2, 'best-count-pearson'),
    ('ATAC', 'adrenal gland'): ('ENCSR414DVK', 8, 'best-count-pearson'),
    ('ATAC', 'aorta'): ('ENCSR295TFY', 1, 'only-candidate'),
    ('ATAC', 'bile duct'): ('ENCSR174MLD', 3, 'best-count-pearson'),
    ('ATAC', 'body of pancreas'): ('ENCSR773USD', 4, 'best-count-pearson'),
    ('ATAC', 'breast epithelium'): ('ENCSR654UYP', 3, 'best-count-pearson'),
    ('ATAC', 'cardiac septum'): ('ENCSR167SYF', 1, 'only-candidate'),
    ('ATAC', 'central memory CD8-positive, alpha-beta T cell'): ('ENCSR165FYY', 1, 'only-candidate'),
    ('ATAC', 'cerebellum'): ('ENCSR802GEV', 1, 'only-candidate'),
    ('ATAC', 'colonic mucosa'): ('ENCSR970UNF', 1, 'only-candidate'),
    ('ATAC', 'coronary artery'): ('ENCSR584AXZ', 1, 'only-candidate'),
    ('ATAC', 'dendritic cell'): ('ENCSR535NOD', 24, 'best-count-pearson'),
    ('ATAC', 'effector memory CD8-positive, alpha-beta T cell'): ('ENCSR019XCN', 2, 'best-count-pearson'),
    ('ATAC', 'esophagus mucosa'): ('ENCSR303PWB', 1, 'only-candidate'),
    ('ATAC', 'esophagus muscularis mucosa'): ('ENCSR609GST', 1, 'only-candidate'),
    ('ATAC', 'esophagus squamous epithelium'): ('ENCSR096BPX', 1, 'only-candidate'),
    ('ATAC', 'fallopian tube'): ('ENCSR565DSD', 3, 'best-count-pearson'),
    ('ATAC', 'foreskin keratinocyte'): ('ENCSR356KRQ', 1, 'only-candidate'),
    ('ATAC', 'gastrocnemius medialis'): ('ENCSR823ZCR', 4, 'best-count-pearson'),
    ('ATAC', 'gastroesophageal sphincter'): ('ENCSR260ZIV', 2, 'best-count-pearson'),
    ('ATAC', 'heart left ventricle'): ('ENCSR851EBF', 15, 'best-count-pearson'),
    ('ATAC', 'heart right ventricle'): ('ENCSR403GBR', 14, 'best-count-pearson'),
    ('ATAC', 'jejunum'): ('ENCSR415LEB', 1, 'only-candidate'),
    ('ATAC', 'kidney'): ('ENCSR297VGU', 1, 'only-candidate'),
    ('ATAC', 'left cardiac atrium'): ('ENCSR736CIN', 5, 'best-count-pearson'),
    ('ATAC', 'left colon'): ('ENCSR600ZHS', 1, 'only-candidate'),
    ('ATAC', 'left lobe of liver'): ('ENCSR624ODL', 1, 'only-candidate'),
    ('ATAC', 'left lung'): ('ENCSR682ETE', 1, 'only-candidate'),
    ('ATAC', 'left ventricle myocardium inferior'): ('ENCSR946MAI', 1, 'only-candidate'),
    ('ATAC', 'left ventricle myocardium superior'): ('ENCSR133WJY', 1, 'only-candidate'),
    ('ATAC', 'liver'): ('ENCSR124NNL', 1, 'only-candidate'),
    ('ATAC', 'lower lobe of left lung'): ('ENCSR555ZDH', 1, 'only-candidate'),
    ('ATAC', 'lower lobe of right lung'): ('ENCSR923VTG', 2, 'best-count-pearson'),
    ('ATAC', 'lung'): ('ENCSR647AOY', 1, 'only-candidate'),
    ('ATAC', 'memory B cell'): ('ENCSR610AQP', 1, 'only-candidate'),
    ('ATAC', 'mesenteric fat pad'): ('ENCSR551CSY', 1, 'only-candidate'),
    ('ATAC', 'motor neuron'): ('ENCSR709QRD', 10, 'best-count-pearson'),
    ('ATAC', 'mucosa of descending colon'): ('ENCSR496PPU', 2, 'best-count-pearson'),
    ('ATAC', 'mucosa of gallbladder'): ('ENCSR695FLC', 1, 'only-candidate'),
    ('ATAC', 'mucosa of urinary bladder'): ('ENCSR548SSP', 2, 'best-count-pearson'),
    ('ATAC', 'naive B cell'): ('ENCSR903WVU', 2, 'best-count-pearson'),
    ('ATAC', 'naive thymus-derived CD4-positive, alpha-beta T cell'): ('ENCSR452COS', 2, 'best-count-pearson'),
    ('ATAC', 'naive thymus-derived CD8-positive, alpha-beta T cell'): ('ENCSR513EVP', 3, 'best-count-pearson'),
    ('ATAC', 'natural killer cell'): ('ENCSR808HWS', 5, 'best-count-pearson'),
    ('ATAC', 'omental fat pad'): ('ENCSR788TRR', 1, 'only-candidate'),
    ('ATAC', 'ovary'): ('ENCSR490MSG', 7, 'best-count-pearson'),
    ('ATAC', 'pancreas'): ('ENCSR808ZMK', 5, 'best-count-pearson'),
    ('ATAC', 'posterior cingulate cortex'): ('ENCSR729FNL', 1, 'only-candidate'),
    ('ATAC', 'posterior vena cava'): ('ENCSR913FZQ', 3, 'best-count-pearson'),
    ('ATAC', 'prostate gland'): ('ENCSR999NKW', 1, 'only-candidate'),
    ('ATAC', 'psoas muscle'): ('ENCSR154UWN', 5, 'best-count-pearson'),
    ('ATAC', 'right atrium auricular region'): ('ENCSR062SVK', 1, 'only-candidate'),
    ('ATAC', 'right cardiac atrium'): ('ENCSR452OSK', 4, 'best-count-pearson'),
    ('ATAC', 'right lobe of liver'): ('ENCSR373TDL', 6, 'best-count-pearson'),
    ('ATAC', 'sciatic nerve'): ('ENCSR533WFB', 4, 'best-count-pearson'),
    ('ATAC', 'sigmoid colon'): ('ENCSR086OGH', 4, 'best-count-pearson'),
    ('ATAC', 'spleen'): ('ENCSR182VGJ', 5, 'best-count-pearson'),
    ('ATAC', 'stimulated activated effector memory CD8-positive, alpha-beta T cell'): ('ENCSR335LHS', 2, 'best-count-pearson'),
    ('ATAC', 'stimulated activated memory B cell'): ('ENCSR302PTB', 1, 'only-candidate'),
    ('ATAC', 'stimulated activated naive B cell'): ('ENCSR379NMT', 2, 'best-count-pearson'),
    ('ATAC', 'stimulated activated naive CD8-positive, alpha-beta T cell'): ('ENCSR637OPZ', 3, 'best-count-pearson'),
    ('ATAC', 'stomach'): ('ENCSR851SBY', 2, 'best-count-pearson'),
    ('ATAC', 'subcutaneous adipose tissue'): ('ENCSR540BML', 1, 'only-candidate'),
    ('ATAC', 'testis'): ('ENCSR210NKB', 1, 'only-candidate'),
    ('ATAC', 'thoracic aorta'): ('ENCSR344ZTM', 1, 'only-candidate'),
    ('ATAC', 'thyroid gland'): ('ENCSR914DTI', 3, 'best-count-pearson'),
    ('ATAC', 'tibial artery'): ('ENCSR630REB', 1, 'only-candidate'),
    ('ATAC', 'tibial nerve'): ('ENCSR831KAH', 1, 'only-candidate'),
    ('ATAC', 'transverse colon'): ('ENCSR761TKU', 4, 'best-count-pearson'),
    ('ATAC', 'upper lobe of left lung'): ('ENCSR895SEG', 2, 'best-count-pearson'),
    ('ATAC', 'upper lobe of right lung'): ('ENCSR990NNX', 1, 'only-candidate'),
    ('ATAC', 'ureter'): ('ENCSR814RGG', 1, 'only-candidate'),
    ('ATAC', 'uterus'): ('ENCSR705RZX', 2, 'best-count-pearson'),
    ('DNASE', 'A172'): ('ENCSR932KWJ', 1, 'only-candidate'),
    ('DNASE', 'A549'): ('ENCSR000ELW', 1, 'only-candidate'),
    ('DNASE', 'A673'): ('ENCSR346JWH', 1, 'only-candidate'),
    ('DNASE', 'ACHN'): ('ENCSR257BGZ', 1, 'only-candidate'),
    ('DNASE', 'AG04449'): ('ENCSR000ELX', 1, 'only-candidate'),
    ('DNASE', 'AG04450'): ('ENCSR000ELY', 1, 'only-candidate'),
    ('DNASE', 'AG09319'): ('ENCSR000EMA', 1, 'only-candidate'),
    ('DNASE', 'AG10803'): ('ENCSR000EMB', 1, 'only-candidate'),
    ('DNASE', "Ammon's horn"): ('ENCSR584LUZ', 1, 'only-candidate'),
    ('DNASE', 'B cell'): ('ENCSR468AKF', 5, 'best-count-pearson'),
    ('DNASE', 'BE2C'): ('ENCSR009KWQ', 2, 'best-count-pearson'),
    ('DNASE', 'BJ'): ('ENCSR000EME', 1, 'only-candidate'),
    ('DNASE', 'CD14-positive monocyte'): ('ENCSR695AUY', 4, 'best-count-pearson'),
    ('DNASE', 'CD1c-positive myeloid dendritic cell'): ('ENCSR373BIX', 1, 'only-candidate'),
    ('DNASE', 'CD4-positive, CD25-positive, alpha-beta regulatory T cell'): ('ENCSR398CXD', 4, 'best-count-pearson'),
    ('DNASE', 'CD4-positive, alpha-beta T cell'): ('ENCSR289GZQ', 44, 'best-count-pearson'),
    ('DNASE', 'CD4-positive, alpha-beta memory T cell'): ('ENCSR239XNU', 1, 'only-candidate'),
    ('DNASE', 'CD8-positive, alpha-beta T cell'): ('ENCSR097AMI', 19, 'best-count-pearson'),
    ('DNASE', 'CD8-positive, alpha-beta memory T cell'): ('ENCSR625WLB', 3, 'best-count-pearson'),
    ('DNASE', 'CMK'): ('ENCSR000EMN', 1, 'only-candidate'),
    ('DNASE', 'Caco-2'): ('ENCSR000EMI', 2, 'best-count-pearson'),
    ('DNASE', 'Caki2'): ('ENCSR515EWI', 1, 'only-candidate'),
    ('DNASE', 'DND-41'): ('ENCSR903SKE', 1, 'only-candidate'),
    ('DNASE', 'Daoy'): ('ENCSR346IHH', 1, 'only-candidate'),
    ('DNASE', 'EH'): ('ENCSR548MMD', 1, 'only-candidate'),
    ('DNASE', 'EL'): ('ENCSR691MQJ', 1, 'only-candidate'),
    ('DNASE', 'ELF-1'): ('ENCSR678ILN', 1, 'only-candidate'),
    ('DNASE', 'ELR'): ('ENCSR240TPI', 1, 'only-candidate'),
    ('DNASE', 'G401'): ('ENCSR269SIA', 1, 'only-candidate'),
    ('DNASE', 'GM04503'): ('ENCSR000EMO', 1, 'only-candidate'),
    ('DNASE', 'GM04504'): ('ENCSR000EMP', 1, 'only-candidate'),
    ('DNASE', 'GM06990'): ('ENCSR000EMQ', 1, 'only-candidate'),
    ('DNASE', 'GM12864'): ('ENCSR000EMR', 1, 'only-candidate'),
    ('DNASE', 'GM12865'): ('ENCSR000EMS', 1, 'only-candidate'),
    ('DNASE', 'GM12878'): ('ENCSR000EMT', 1, 'chrombpnet-parity'),
    ('DNASE', 'GM23248'): ('ENCSR217TAW', 1, 'only-candidate'),
    ('DNASE', 'GM23338'): ('ENCSR108PUO', 2, 'best-count-pearson'),
    ('DNASE', 'H1'): ('ENCSR000EMU', 1, 'chrombpnet-parity'),
    ('DNASE', 'H4'): ('ENCSR809CEA', 1, 'only-candidate'),
    ('DNASE', 'H7'): ('ENCSR000EMZ', 1, 'only-candidate'),
    ('DNASE', 'H9'): ('ENCSR662RIZ', 6, 'best-count-pearson'),
    ('DNASE', 'HAP-1'): ('ENCSR895KTN', 2, 'best-count-pearson'),
    ('DNASE', 'HCEC 1CT'): ('ENCSR038XTK', 1, 'only-candidate'),
    ('DNASE', 'HCT116'): ('ENCSR000ENM', 1, 'only-candidate'),
    ('DNASE', 'HFF-Myc'): ('ENCSR000ENR', 1, 'only-candidate'),
    ('DNASE', 'HFFc6'): ('ENCSR672EWY', 1, 'only-candidate'),
    ('DNASE', 'HK-2'): ('ENCSR634YVQ', 1, 'only-candidate'),
    ('DNASE', 'HL-60'): ('ENCSR889WKL', 2, 'best-count-pearson'),
    ('DNASE', 'HS-27A'): ('ENCSR000EMF', 1, 'only-candidate'),
    ('DNASE', 'HS-5'): ('ENCSR000EMG', 1, 'only-candidate'),
    ('DNASE', 'HT-29'): ('ENCSR814KRX', 1, 'only-candidate'),
    ('DNASE', 'HT1080'): ('ENCSR000FDI', 1, 'only-candidate'),
    ('DNASE', 'HeLa-S3'): ('ENCSR959ZXU', 2, 'best-count-pearson'),
    ('DNASE', 'HepG2'): ('ENCSR149XIL', 1, 'chrombpnet-parity'),
    ('DNASE', 'IMR-90'): ('ENCSR477RTP', 1, 'chrombpnet-parity'),
    ('DNASE', 'Jurkat, Clone E6-1'): ('ENCSR000EOS', 1, 'only-candidate'),
    ('DNASE', 'K562'): ('ENCSR000EOT', 1, 'chrombpnet-parity'),
    ('DNASE', 'KBM-7'): ('ENCSR426IEA', 1, 'only-candidate'),
    ('DNASE', 'Karpas-422'): ('ENCSR019JDO', 1, 'only-candidate'),
    ('DNASE', 'L1-S8'): ('ENCSR314EZY', 1, 'only-candidate'),
    ('DNASE', 'L1-S8R'): ('ENCSR746ZPP', 1, 'only-candidate'),
    ('DNASE', 'LHCN-M2'): ('ENCSR000EPE', 1, 'only-candidate'),
    ('DNASE', 'LoVo'): ('ENCSR503BEM', 1, 'only-candidate'),
    ('DNASE', 'MCF 10A'): ('ENCSR385SZQ', 3, 'best-count-pearson'),
    ('DNASE', 'MCF-7'): ('ENCSR000EPI', 2, 'best-count-pearson'),
    ('DNASE', 'MG63'): ('ENCSR443YJP', 2, 'best-count-pearson'),
    ('DNASE', 'MM.1S'): ('ENCSR458LIB', 1, 'only-candidate'),
    ('DNASE', 'NAMALWA'): ('ENCSR301OGM', 2, 'best-count-pearson'),
    ('DNASE', 'NB4'): ('ENCSR000EPL', 1, 'only-candidate'),
    ('DNASE', 'NCI-H226'): ('ENCSR265TEK', 1, 'only-candidate'),
    ('DNASE', 'NCI-H460'): ('ENCSR000FJH', 1, 'only-candidate'),
    ('DNASE', 'NCI-H929'): ('ENCSR090SMP', 1, 'only-candidate'),
    ('DNASE', 'NT2/D1'): ('ENCSR000EPS', 1, 'only-candidate'),
    ('DNASE', 'OCI-LY7'): ('ENCSR489NAM', 1, 'only-candidate'),
    ('DNASE', 'PC-3'): ('ENCSR052AWE', 1, 'only-candidate'),
    ('DNASE', 'PC-9'): ('ENCSR940NLN', 1, 'only-candidate'),
    ('DNASE', 'Panc1'): ('ENCSR000EPT', 1, 'only-candidate'),
    ('DNASE', "Peyer's patch"): ('ENCSR954AJK', 4, 'best-count-pearson'),
    ('DNASE', 'RCC'): ('ENCSR337IRF', 1, 'only-candidate'),
    ('DNASE', 'RCC 7860'): ('ENCSR037PGI', 1, 'only-candidate'),
    ('DNASE', 'RKO'): ('ENCSR429RHR', 1, 'only-candidate'),
    ('DNASE', 'RPMI7951'): ('ENCSR000EPV', 1, 'only-candidate'),
    ('DNASE', 'RPMI8226'): ('ENCSR594NOE', 1, 'only-candidate'),
    ('DNASE', 'RWPE2'): ('ENCSR306BHE', 1, 'only-candidate'),
    ('DNASE', 'Right ventricle myocardium inferior'): ('ENCSR085MZL', 1, 'only-candidate'),
    ('DNASE', 'Right ventricle myocardium superior'): ('ENCSR895GSY', 1, 'only-candidate'),
    ('DNASE', 'SJCRH30'): ('ENCSR000FFJ', 1, 'only-candidate'),
    ('DNASE', 'SJSA1'): ('ENCSR520WTV', 2, 'best-count-pearson'),
    ('DNASE', 'SK-MEL-5'): ('ENCSR000FEK', 1, 'only-candidate'),
    ('DNASE', 'SK-N-DZ'): ('ENCSR946MVP', 1, 'only-candidate'),
    ('DNASE', 'SK-N-MC'): ('ENCSR000EPY', 1, 'only-candidate'),
    ('DNASE', 'SK-N-SH'): ('ENCSR000EPZ', 1, 'only-candidate'),
    ('DNASE', 'SW480'): ('ENCSR217SET', 1, 'only-candidate'),
    ('DNASE', 'T-cell'): ('ENCSR051CYH', 58, 'best-count-pearson'),
    ('DNASE', 'T-helper 1 cell'): ('ENCSR453RFW', 7, 'best-count-pearson'),
    ('DNASE', 'T-helper 17 cell'): ('ENCSR747RGR', 6, 'best-count-pearson'),
    ('DNASE', 'T-helper 2 cell'): ('ENCSR872IXQ', 7, 'best-count-pearson'),
    ('DNASE', 'T47D'): ('ENCSR000EQB', 1, 'only-candidate'),
    ('DNASE', 'WERI-Rb-1'): ('ENCSR218FSP', 2, 'best-count-pearson'),
    ('DNASE', 'WI38'): ('ENCSR000EQM', 2, 'best-count-pearson'),
    ('DNASE', 'WTC11'): ('ENCSR785ZUI', 1, 'only-candidate'),
    ('DNASE', 'activated B cell'): ('ENCSR109DTU', 1, 'only-candidate'),
    ('DNASE', 'activated CD4-positive, CD25-positive, alpha-beta regulatory T cell'): ('ENCSR242CLA', 2, 'best-count-pearson'),
    ('DNASE', 'activated CD4-positive, alpha-beta T cell'): ('ENCSR799MVH', 24, 'best-count-pearson'),
    ('DNASE', 'activated CD4-positive, alpha-beta memory T cell'): ('ENCSR021YFW', 1, 'only-candidate'),
    ('DNASE', 'activated CD8-positive, alpha-beta T cell'): ('ENCSR776BTO', 2, 'best-count-pearson'),
    ('DNASE', 'activated CD8-positive, alpha-beta memory T cell'): ('ENCSR933VOY', 13, 'best-count-pearson'),
    ('DNASE', 'activated T-cell'): ('ENCSR273GCF', 13, 'best-count-pearson'),
    ('DNASE', 'activated T-helper 1 cell'): ('ENCSR636DIR', 1, 'only-candidate'),
    ('DNASE', 'activated T-helper 2 cell'): ('ENCSR780ABS', 1, 'only-candidate'),
    ('DNASE', 'activated naive CD4-positive, alpha-beta T cell'): ('ENCSR515PDV', 7, 'best-count-pearson'),
    ('DNASE', 'activated naive CD8-positive, alpha-beta T cell'): ('ENCSR009MDC', 4, 'best-count-pearson'),
    ('DNASE', 'adipocyte'): ('ENCSR405TXU', 1, 'only-candidate'),
    ('DNASE', 'adrenal gland'): ('ENCSR962VJO', 14, 'best-count-pearson'),
    ('DNASE', 'amniotic stem cell'): ('ENCSR207TUX', 1, 'only-candidate'),
    ('DNASE', 'aorta'): ('ENCSR595DQM', 2, 'best-count-pearson'),
    ('DNASE', 'ascending aorta'): ('ENCSR968TPO', 2, 'best-count-pearson'),
    ('DNASE', 'astrocyte'): ('ENCSR146KFX', 2, 'best-count-pearson'),
    ('DNASE', 'astrocyte of the cerebellum'): ('ENCSR000ENC', 1, 'only-candidate'),
    ('DNASE', 'astrocyte of the hippocampus'): ('ENCSR000ENA', 1, 'only-candidate'),
    ('DNASE', 'astrocyte of the spinal cord'): ('ENCSR000ENB', 1, 'only-candidate'),
    ('DNASE', 'body of pancreas'): ('ENCSR464TKV', 4, 'best-count-pearson'),
    ('DNASE', 'brain'): ('ENCSR330JXM', 13, 'best-count-pearson'),
    ('DNASE', 'brain microvascular endothelial cell'): ('ENCSR000ENE', 1, 'only-candidate'),
    ('DNASE', 'brain pericyte'): ('ENCSR000ENF', 1, 'only-candidate'),
    ('DNASE', 'breast epithelium'): ('ENCSR859LTL', 1, 'only-candidate'),
    ('DNASE', 'cardiac fibroblast'): ('ENCSR856NXV', 2, 'best-count-pearson'),
    ('DNASE', 'cardiac muscle cell'): ('ENCSR842KCP', 1, 'only-candidate'),
    ('DNASE', 'cardiac septum'): ('ENCSR524QBS', 1, 'only-candidate'),
    ('DNASE', 'caudate nucleus'): ('ENCSR015BGH', 1, 'only-candidate'),
    ('DNASE', 'cerebellar cortex'): ('ENCSR503HIB', 1, 'only-candidate'),
    ('DNASE', 'colonic mucosa'): ('ENCSR994KTY', 2, 'best-count-pearson'),
    ('DNASE', 'common myeloid progenitor, CD34-positive'): ('ENCSR772HUG', 11, 'best-count-pearson'),
    ('DNASE', 'dedifferentiated amniotic fluid mesenchymal stem cell'): ('ENCSR820WLP', 1, 'only-candidate'),
    ('DNASE', 'dermis blood vessel endothelial cell'): ('ENCSR000ENX', 3, 'best-count-pearson'),
    ('DNASE', 'dermis microvascular lymphatic vessel endothelial cell'): ('ENCSR000EOB', 2, 'best-count-pearson'),
    ('DNASE', 'dorsolateral prefrontal cortex'): ('ENCSR796YOJ', 49, 'best-count-pearson'),
    ('DNASE', 'ecto neural progenitor cell'): ('ENCSR360XIS', 1, 'only-candidate'),
    ('DNASE', 'effector memory CD4-positive, alpha-beta T cell'): ('ENCSR724INK', 3, 'best-count-pearson'),
    ('DNASE', 'embryonic facial prominence'): ('ENCSR435NHO', 1, 'only-candidate'),
    ('DNASE', 'endodermal cell'): ('ENCSR940CXU', 2, 'best-count-pearson'),
    ('DNASE', 'endothelial cell'): ('ENCSR541IET', 1, 'only-candidate'),
    ('DNASE', 'endothelial cell of umbilical vein'): ('ENCSR000EOQ', 1, 'only-candidate'),
    ('DNASE', 'epithelial cell of prostate'): ('ENCSR000EPU', 1, 'only-candidate'),
    ('DNASE', 'eye'): ('ENCSR127PWK', 1, 'only-candidate'),
    ('DNASE', 'femur'): ('ENCSR805XIF', 1, 'only-candidate'),
    ('DNASE', 'fibroblast of gingiva'): ('ENCSR000ENS', 1, 'only-candidate'),
    ('DNASE', 'fibroblast of lung'): ('ENCSR000EOJ', 1, 'only-candidate'),
    ('DNASE', 'fibroblast of mammary gland'): ('ENCSR000ENW', 1, 'only-candidate'),
    ('DNASE', 'fibroblast of pulmonary artery'): ('ENCSR000EOH', 1, 'only-candidate'),
    ('DNASE', 'fibroblast of skin of abdomen'): ('ENCSR622TWS', 2, 'best-count-pearson'),
    ('DNASE', 'fibroblast of skin of back'): ('ENCSR184LMY', 1, 'only-candidate'),
    ('DNASE', 'fibroblast of skin of left biceps'): ('ENCSR648GDP', 2, 'best-count-pearson'),
    ('DNASE', 'fibroblast of skin of left quadriceps'): ('ENCSR555TFE', 2, 'best-count-pearson'),
    ('DNASE', 'fibroblast of skin of right biceps'): ('ENCSR383BLX', 1, 'only-candidate'),
    ('DNASE', 'fibroblast of skin of right quadriceps'): ('ENCSR217RVH', 1, 'only-candidate'),
    ('DNASE', 'fibroblast of skin of scalp'): ('ENCSR770DEN', 2, 'best-count-pearson'),
    ('DNASE', 'fibroblast of the conjunctiva'): ('ENCSR000ENK', 1, 'only-candidate'),
    ('DNASE', 'fibroblast of upper back skin'): ('ENCSR325LYJ', 2, 'best-count-pearson'),
    ('DNASE', 'fibroblast of villous mesenchyme'): ('ENCSR000EOR', 1, 'only-candidate'),
    ('DNASE', 'forelimb muscle'): ('ENCSR166TEE', 1, 'only-candidate'),
    ('DNASE', 'foreskin fibroblast'): ('ENCSR000ENQ', 3, 'best-count-pearson'),
    ('DNASE', 'foreskin keratinocyte'): ('ENCSR724CND', 1, 'only-candidate'),
    ('DNASE', 'foreskin melanocyte'): ('ENCSR434OBM', 2, 'best-count-pearson'),
    ('DNASE', 'gastrocnemius medialis'): ('ENCSR686WJL', 4, 'best-count-pearson'),
    ('DNASE', 'globus pallidus'): ('ENCSR771DAX', 1, 'only-candidate'),
    ('DNASE', 'glomerular endothelial cell'): ('ENCSR000EOM', 1, 'only-candidate'),
    ('DNASE', 'glutamatergic neuron'): ('ENCSR109RIQ', 1, 'only-candidate'),
    ('DNASE', 'head of caudate nucleus'): ('ENCSR797FIM', 83, 'best-count-pearson'),
    ('DNASE', 'heart'): ('ENCSR536NGW', 16, 'best-count-pearson'),
    ('DNASE', 'heart left ventricle'): ('ENCSR598RVJ', 10, 'best-count-pearson'),
    ('DNASE', 'heart right ventricle'): ('ENCSR356RNZ', 10, 'best-count-pearson'),
    ('DNASE', 'hematopoietic multipotent progenitor cell'): ('ENCSR328UMC', 12, 'best-count-pearson'),
    ('DNASE', 'hepatocyte'): ('ENCSR364MFN', 1, 'only-candidate'),
    ('DNASE', 'hindlimb muscle'): ('ENCSR385AMY', 1, 'only-candidate'),
    ('DNASE', 'iPS DF 19.11'): ('ENCSR383SNM', 1, 'only-candidate'),
    ('DNASE', 'iPS DF 19.7'): ('ENCSR440QMR', 1, 'only-candidate'),
    ('DNASE', 'iPS DF 4.7'): ('ENCSR014FPY', 1, 'only-candidate'),
    ('DNASE', 'iPS DF 6.9'): ('ENCSR261SMF', 1, 'only-candidate'),
    ('DNASE', 'inferior parietal cortex'): ('ENCSR986YWZ', 1, 'only-candidate'),
    ('DNASE', 'islet precursor cell'): ('ENCSR224FOA', 1, 'only-candidate'),
    ('DNASE', 'keratinocyte'): ('ENCSR000EPQ', 1, 'only-candidate'),
    ('DNASE', 'kidney'): ('ENCSR206OJJ', 14, 'best-count-pearson'),
    ('DNASE', 'kidney capillary endothelial cell'): ('ENCSR988YKR', 1, 'only-candidate'),
    ('DNASE', 'kidney glomerular epithelial cell'): ('ENCSR136KEL', 1, 'only-candidate'),
    ('DNASE', 'large intestine'): ('ENCSR366EQH', 14, 'best-count-pearson'),
    ('DNASE', 'left cardiac atrium'): ('ENCSR032NNU', 1, 'only-candidate'),
    ('DNASE', 'left colon'): ('ENCSR279SXQ', 2, 'best-count-pearson'),
    ('DNASE', 'left forelimb'): ('ENCSR976XOY', 1, 'only-candidate'),
    ('DNASE', 'left hindlimb'): ('ENCSR431UEM', 1, 'only-candidate'),
    ('DNASE', 'left kidney'): ('ENCSR953XJU', 9, 'best-count-pearson'),
    ('DNASE', 'left lobe of liver'): ('ENCSR802ZYE', 1, 'only-candidate'),
    ('DNASE', 'left lung'): ('ENCSR658UBE', 11, 'best-count-pearson'),
    ('DNASE', 'left renal cortex interstitium'): ('ENCSR039ZVQ', 4, 'best-count-pearson'),
    ('DNASE', 'left renal pelvis'): ('ENCSR320SVK', 4, 'best-count-pearson'),
    ('DNASE', 'left ventricle myocardium inferior'): ('ENCSR770OTB', 1, 'only-candidate'),
    ('DNASE', 'left ventricle myocardium superior'): ('ENCSR355WAJ', 1, 'only-candidate'),
    ('DNASE', 'limb'): ('ENCSR818JGZ', 2, 'best-count-pearson'),
    ('DNASE', 'liver'): ('ENCSR562FNN', 2, 'best-count-pearson'),
    ('DNASE', 'lower leg skin'): ('ENCSR361DND', 1, 'only-candidate'),
    ('DNASE', 'lower lobe of left lung'): ('ENCSR632ONQ', 2, 'best-count-pearson'),
    ('DNASE', 'lower lobe of right lung'): ('ENCSR785JXR', 1, 'only-candidate'),
    ('DNASE', 'lung'): ('ENCSR945JJB', 11, 'best-count-pearson'),
    ('DNASE', 'lung microvascular endothelial cell'): ('ENCSR000EOE', 2, 'best-count-pearson'),
    ('DNASE', 'mammary epithelial cell'): ('ENCSR817ALC', 2, 'best-count-pearson'),
    ('DNASE', 'medulla oblongata'): ('ENCSR224IYD', 1, 'only-candidate'),
    ('DNASE', 'memory B cell'): ('ENCSR736VVP', 2, 'best-count-pearson'),
    ('DNASE', 'mesenchymal stem cell'): ('ENCSR731QLJ', 1, 'only-candidate'),
    ('DNASE', 'mesendoderm'): ('ENCSR714DIF', 1, 'only-candidate'),
    ('DNASE', 'mesothelial cell of epicardium'): ('ENCSR945KSP', 1, 'only-candidate'),
    ('DNASE', 'midbrain'): ('ENCSR706IDL', 1, 'only-candidate'),
    ('DNASE', 'middle frontal gyrus'): ('ENCSR318PRQ', 1, 'only-candidate'),
    ('DNASE', 'mucosa of descending colon'): ('ENCSR404TSP', 3, 'best-count-pearson'),
    ('DNASE', 'mucosa of gallbladder'): ('ENCSR011SAG', 1, 'only-candidate'),
    ('DNASE', 'muscle of arm'): ('ENCSR357PMV', 15, 'best-count-pearson'),
    ('DNASE', 'muscle of back'): ('ENCSR010ZMK', 13, 'best-count-pearson'),
    ('DNASE', 'muscle of leg'): ('ENCSR198JXW', 12, 'best-count-pearson'),
    ('DNASE', 'muscle of trunk'): ('ENCSR411MGY', 3, 'best-count-pearson'),
    ('DNASE', 'myocyte'): ('ENCSR000EPD', 1, 'only-candidate'),
    ('DNASE', 'myotube'): ('ENCSR000EOP', 1, 'only-candidate'),
    ('DNASE', 'naive B cell'): ('ENCSR480SNC', 2, 'best-count-pearson'),
    ('DNASE', 'naive thymus-derived CD4-positive, alpha-beta T cell'): ('ENCSR125OEJ', 7, 'best-count-pearson'),
    ('DNASE', 'naive thymus-derived CD8-positive, alpha-beta T cell'): ('ENCSR237BOF', 8, 'best-count-pearson'),
    ('DNASE', 'natural killer cell'): ('ENCSR794TLA', 7, 'best-count-pearson'),
    ('DNASE', 'nephron progenitor cell'): ('ENCSR503UNA', 1, 'only-candidate'),
    ('DNASE', 'neural crest cell'): ('ENCSR826URD', 1, 'only-candidate'),
    ('DNASE', 'neural progenitor cell'): ('ENCSR963ALV', 1, 'only-candidate'),
    ('DNASE', 'neuronal stem cell'): ('ENCSR278FVO', 1, 'only-candidate'),
    ('DNASE', 'omental fat pad'): ('ENCSR693UHT', 1, 'only-candidate'),
    ('DNASE', 'osteocyte'): ('ENCSR818HHN', 1, 'only-candidate'),
    ('DNASE', 'ovary'): ('ENCSR365NDK', 9, 'best-count-pearson'),
    ('DNASE', 'pancreas'): ('ENCSR338NEI', 7, 'best-count-pearson'),
    ('DNASE', 'placenta'): ('ENCSR552RKI', 22, 'best-count-pearson'),
    ('DNASE', 'pons'): ('ENCSR829MXU', 1, 'only-candidate'),
    ('DNASE', 'posterior cingulate gyrus'): ('ENCSR628GQE', 43, 'best-count-pearson'),
    ('DNASE', 'posterior vena cava'): ('ENCSR324NVG', 1, 'only-candidate'),
    ('DNASE', 'progenitor cell of endocrine pancreas'): ('ENCSR169KNO', 1, 'only-candidate'),
    ('DNASE', 'prostate gland'): ('ENCSR564FZH', 1, 'only-candidate'),
    ('DNASE', 'psoas muscle'): ('ENCSR082PDJ', 4, 'best-count-pearson'),
    ('DNASE', 'pulmonary artery endothelial cell'): ('ENCSR000EOG', 1, 'only-candidate'),
    ('DNASE', 'putamen'): ('ENCSR493VDS', 1, 'only-candidate'),
    ('DNASE', 'renal cortex interstitium'): ('ENCSR550UWM', 11, 'best-count-pearson'),
    ('DNASE', 'renal cortical epithelial cell'): ('ENCSR000EOK', 1, 'only-candidate'),
    ('DNASE', 'renal pelvis'): ('ENCSR619DRM', 10, 'best-count-pearson'),
    ('DNASE', 'retina'): ('ENCSR621ENC', 3, 'best-count-pearson'),
    ('DNASE', 'right atrium auricular region'): ('ENCSR984SQJ', 1, 'only-candidate'),
    ('DNASE', 'right cardiac atrium'): ('ENCSR374VQC', 3, 'best-count-pearson'),
    ('DNASE', 'right forelimb'): ('ENCSR274SDO', 1, 'only-candidate'),
    ('DNASE', 'right hindlimb'): ('ENCSR449HOQ', 1, 'only-candidate'),
    ('DNASE', 'right kidney'): ('ENCSR768OLL', 10, 'best-count-pearson'),
    ('DNASE', 'right lobe of liver'): ('ENCSR608NWP', 5, 'best-count-pearson'),
    ('DNASE', 'right lung'): ('ENCSR859KGQ', 7, 'best-count-pearson'),
    ('DNASE', 'right renal cortex interstitium'): ('ENCSR887BNC', 3, 'best-count-pearson'),
    ('DNASE', 'right renal pelvis'): ('ENCSR752NTF', 4, 'best-count-pearson'),
    ('DNASE', 'sciatic nerve'): ('ENCSR672MOG', 1, 'only-candidate'),
    ('DNASE', 'sigmoid colon'): ('ENCSR276ITP', 1, 'only-candidate'),
    ('DNASE', 'skeletal muscle cell'): ('ENCSR000EQA', 1, 'only-candidate'),
    ('DNASE', 'skeletal muscle myoblast'): ('ENCSR000EOO', 1, 'only-candidate'),
    ('DNASE', 'skin of body'): ('ENCSR092OFK', 1, 'only-candidate'),
    ('DNASE', 'small intestine'): ('ENCSR133KBX', 12, 'best-count-pearson'),
    ('DNASE', 'smooth muscle cell of the brain vasculature'): ('ENCSR000ENG', 1, 'only-candidate'),
    ('DNASE', 'spinal cord'): ('ENCSR615WIN', 6, 'best-count-pearson'),
    ('DNASE', 'spleen'): ('ENCSR567EEO', 5, 'best-count-pearson'),
    ('DNASE', 'stimulated activated CD4-positive, alpha-beta T cell'): ('ENCSR531UVE', 55, 'best-count-pearson'),
    ('DNASE', 'stimulated activated CD8-positive, alpha-beta memory T cell'): ('ENCSR135XMY', 26, 'best-count-pearson'),
    ('DNASE', 'stimulated activated effector memory CD8-positive, alpha-beta T cell'): ('ENCSR917BSW', 1, 'only-candidate'),
    ('DNASE', 'stimulated activated naive CD8-positive, alpha-beta T cell'): ('ENCSR208YDK', 3, 'best-count-pearson'),
    ('DNASE', 'stomach'): ('ENCSR163PKT', 20, 'best-count-pearson'),
    ('DNASE', 'stromal cell of bone marrow'): ('ENCSR000EMH', 1, 'only-candidate'),
    ('DNASE', 'superior temporal gyrus'): ('ENCSR382JUJ', 1, 'only-candidate'),
    ('DNASE', 'suprapubic skin'): ('ENCSR101QXF', 1, 'only-candidate'),
    ('DNASE', 'testis'): ('ENCSR866ODX', 3, 'best-count-pearson'),
    ('DNASE', 'thoracic aorta'): ('ENCSR298SDT', 1, 'only-candidate'),
    ('DNASE', 'thymus'): ('ENCSR838IPF', 9, 'best-count-pearson'),
    ('DNASE', 'thyroid gland'): ('ENCSR195ONB', 3, 'best-count-pearson'),
    ('DNASE', 'tibial artery'): ('ENCSR090IDV', 2, 'best-count-pearson'),
    ('DNASE', 'tibial nerve'): ('ENCSR508FVM', 2, 'best-count-pearson'),
    ('DNASE', 'tongue'): ('ENCSR559WMK', 2, 'best-count-pearson'),
    ('DNASE', 'transverse colon'): ('ENCSR340MRJ', 3, 'best-count-pearson'),
    ('DNASE', 'trophoblast cell'): ('ENCSR964MZQ', 5, 'best-count-pearson'),
    ('DNASE', 'type B pancreatic cell'): ('ENCSR362ZFC', 1, 'only-candidate'),
    ('DNASE', 'umbilical cord'): ('ENCSR512CWR', 1, 'only-candidate'),
    ('DNASE', 'upper lobe of left lung'): ('ENCSR702DPD', 5, 'best-count-pearson'),
    ('DNASE', 'upper lobe of right lung'): ('ENCSR357AWH', 1, 'only-candidate'),
    ('DNASE', 'ureter'): ('ENCSR398JUP', 1, 'only-candidate'),
    ('DNASE', 'urinary bladder'): ('ENCSR813CKU', 1, 'only-candidate'),
    ('DNASE', 'uterus'): ('ENCSR545ADK', 2, 'best-count-pearson'),
}
