LEFT_SECOND_MPRA_FLANK = "GGCCCGCTCTAGACCTGCAGG"
RIGHT_SECOND_MPRA_FLANK = "CACTAGAGGGTATATAATGGAAGCTCGACTTCCAGCTTGGCAATCCGGTACTGT"
LEFT_MPRA_FLANK = 'CATTGCGTGAACCGA'
RIGHT_MPRA_FLANK = 'AGGACCGGATCAACT'

SEQUENCE_SIZE = 200